Extra credit
RoodzFernando/rails-forms pull request #6
Opened 2020-01-31 17:41 UTC by RoodzFernando

2020-01-31 22:14 UTC, wathigo requested changes
### Changes Required 
Hi @RoodzFernando  and @firmoholanda :wave: 
We need to meet some requirements before we move on.
See the comments :point_down: 

**After implementing the changes, submit another request for review.**

**Happy Coding  :computer: 
Simon Wathigo**

2020-01-31 22:14 UTC, wathigo commented on config/routes.rb
> +  resources :users
**[REQUIRED]**
*We need `resources :users, only: [:new, :create, :edit, :update]` in config/routes.rb ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/controllers/users_controller.rb
> +  def edit; end
**[REQUIRED]**
* Finds user based on id from params, i.e. `@user = User.find(params[:id])` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/controllers/users_controller.rb
> +  def update; end
**[REQUIRED]**
* Finds user based on id from params, i.e. `@user = User.find(params[:id])` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_params.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)).
* `redirect_to edit_user_path` if user was saved.
* `render :edit` if user was not saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_update.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/views/users/new.html.erb
> +  <div class="field">
**[REQUIRED]**
We need a **commented out** `form` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/controllers/users_controller.rb
> +  def edit; end
**[REQUIRED]**
* Finds user based on id from params, i.e. @user = User.find(params[:id]) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/controllers/users_controller.rb
> +  def update; end
**[REQUIRED]**
* Finds user based on id from params, i.e. `@user = User.find(params[:id])` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_params.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)).
* `redirect_to edit_user_path` if user was saved.
* `render :edit` if user was not saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_update.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/views/users/new.html.erb
> +  <div class="field">
**[REQUIRED]**
* Contains a commented out `form` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)).
* Contains a commented out `form_tag` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_tag2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)).
* Contains `form_for` that uses `@user` from the controller.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_for.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-01-31 22:14 UTC, wathigo commented on app/views/users/edit.html.erb
> +<% end %>
**[REQUIRED]**
* Use `form_for` in `users/edit.html/erb` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form_edit.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-02-03 21:56 UTC, maelfosso requested changes
# changes required :red_circle: 

Hello @RoodzFernando @firmoholanda 

Thank you for the improvements.
However, there are still changes that should be done before you move forward.

1. As @wathigo  said in last review, there is still missing one commented form, the one with `form_tag`.

2.  Read the comments below.

Kindly make the changes and submit a new code review requests.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-02-03 21:56 UTC, maelfosso commented on app/views/users/new.html.erb
> +    <%= f.text_area :email %>
`textarea` is not good for email

2020-02-03 21:56 UTC, maelfosso commented on app/views/users/new.html.erb
> +    <%= f.text_area :password %>
`textarea` is not good for password

2020-02-03 21:56 UTC, maelfosso commented on app/views/users/new.html.erb
> +Email: <input type="email" name="email"><br><br>
Please, I advise you to use `user[username]` and `user[email]`

2020-02-03 22:06 UTC, RoodzFernando commented
Changes implemented!

2020-02-04 12:45 UTC, uche-inyama requested changes
Hi team! :wave: 

Kindly look at my comment below.

If you need any clarifications, please do reachout on slack @ Inyama, Uchechukwu Henry.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-02-04 12:45 UTC, uche-inyama commented on app/views/users/edit.html.erb
> +
Hi, team!

You have not tried out form_tag in this project. Kindly look at this [material](https://api.rubyonrails.org/v5.1.7/classes/ActionView/Helpers/FormTagHelper.html) as a reference. Also, read this [material](https://guides.rubyonrails.org/v3.0/form_helpers.html). Scroll through the web pages carefully to see the topic on form_tag. :slightly_smiling_face:

2020-02-04 20:28 UTC, maelfosso approved these changes
# Congratulations :+1: :clap: 

You can merge it :smile: 
Good luck with the next step

Thanks
**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-02-04 20:34 UTC, merged